---

- name: Configure | fluent-bit main conf
  template:
    src: fluent-bit.conf.j2
    dest: /etc/fluent-bit/fluent-bit.conf
    mode: 0644

- name: Configure | fluent-bit inputs
  template:
    src: 'inputs.conf.j2'
    dest: '/etc/fluent-bit/inputs.conf'
    mode: 0644

- name: Configure | fluent-bit outputs
  template:
    src: 'outputs.conf.j2'
    dest: '/etc/fluent-bit/outputs.conf'
    mode: 0644
  notify: Restart fluentbit service

- name: Configure | fluent-bit filters
  template:
    src: 'filters.conf.j2'
    dest: '/etc/fluent-bit/filters.conf'
    mode: 0644
  when: fluentbit_filters is defined
  notify: Restart fluentbit service

- name: Configure | fluent-bit custom parsers
  template:
    src: 'parsers.conf.j2'
    dest: '/etc/fluent-bit/parsers.conf'
    mode: 0644
  when: fluentbit_custom_parsers is defined
  notify: Restart fluentbit service
