---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'
    - name: Install gpg agent
      ansible.builtin.apt:
        name: gpg-agent
      when: (ansible_os_family | lower) == 'debian'

  roles:
    - role: wpninfra.fluent_bit
