---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -v
platforms:
  # No more tests on old centos7 and amazon linux 2 due cgroups issues https://github.com/geerlingguy/docker-centos7-ansible/issues/22
  #
  # - name: fluentbit_centos7_instance
  #   image: geerlingguy/docker-centos7-ansible:latest
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   tmpfs:
  #     - /run
  #     - /tmp
  #   privileged: true
  #   capabilities:
  #     - SYS_ADMIN
  #     - SETPCAP
  #   pre_build_image: true
  #   cgroupns_mode: host

  - name: fluentbit_amazonlinux2022_instance
    image: geerlingguy/docker-amazonlinux2022-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    capabilities:
      - SYS_ADMIN
      - SETPCAP
    pre_build_image: true
    cgroupns_mode: host

  - name: fluentbit_debian11_instance
    image: geerlingguy/docker-debian11-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    capabilities:
      - SYS_ADMIN
      - SETPCAP
    pre_build_image: true
    cgroupns_mode: host

  - name: fluentbit_centos8_instance
    image: geerlingguy/docker-centos8-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    capabilities:
      - SYS_ADMIN
      - SETPCAP
    pre_build_image: true
    cgroupns_mode: host
  - name: fluentbit_ubuntu_2004_instance
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    capabilities:
      - SYS_ADMIN
      - SETPCAP
    pre_build_image: true
    cgroupns_mode: host

  - name: fluentbit_ubuntu_2204_instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    capabilities:
      - SYS_ADMIN
      - SETPCAP
    pre_build_image: true
    cgroupns_mode: host


  - name: fluentbit_rockylinux8_instance
    image: geerlingguy/docker-rockylinux8-ansible
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    capabilities:
      - SYS_ADMIN
      - SETPCAP
    pre_build_image: true
    cgroupns_mode: host

provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    connection: docker
    v: 2
