---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -v
platforms:
  - name: fluentbit_centos7_instance
    image: geerlingguy/docker-centos7-ansible:latest
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    capabilities:
      - SYS_ADMIN
      - SETPCAP
    pre_build_image: true
    cgroupns_mode: host

  - name: fluentbit_debian11_instance
    image: geerlingguy/docker-debian11-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    capabilities:
      - SYS_ADMIN
      - SETPCAP
    pre_build_image: true
    cgroupns_mode: host

provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    connection: docker
    v: 2
