---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
# TODO  - on
#  ansible-lint -v
platforms:
  # - name: fluentbit_ubuntu_instance_2004
  #   image: geerlingguy/docker-ubuntu2004-ansible
  #   privileged: true
  #   cap_add: ['SYS_ADMIN', 'SETPCAP', 'BPF']
  #   #cap_add: ['ALL', 'SETPCAP', 'BPF']
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   tmpfs:
  #     - /run
  #     - /tmp

  # - name: fluentbit_ubuntu_instance_1804
  #   image: geerlingguy/docker-ubuntu1804-ansible
  #   privileged: true
  #   command: '/sbin/init'
  #   cap_add: ['SYS_ADMIN', 'SETPCAP','BPF']
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  # - name: fluentbit_centos7_instance
  #   image: geerlingguy/docker-centos7-ansible
  #   privileged: true
  #   command: '/sbin/init'
  #   cap_add: ['SYS_ADMIN', 'SETPCAP','BPF']
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  # - name: fluentbit_rockylinux8_instance
  #   image: geerlingguy/docker-rockylinux8-ansible
  #   privileged: true
  #   command: '/sbin/init'
  #   cap_add: ['SYS_ADMIN', 'SETPCAP','BPF']
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  # - name: fluentbit_centos8_instance
  #   image: geerlingguy/docker-centos8-ansible
  #   privileged: true
  #   command: '/sbin/init'
  #   cap_add: ['SYS_ADMIN', 'SETPCAP','BPF']
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  # - name: fluentbit_amazonlinux2_instance
  #   image: geerlingguy/docker-amazonlinux2-ansible
  #   privileged: true
  #   command: '/sbin/init'
  #   cap_add: ['SYS_ADMIN', 'SETPCAP','BPF']
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  # - name: fluentbit_debian_instance_10
  #   image: geerlingguy/docker-debian10-ansible
  #   privileged: true
  #   cap_add: ['SYS_ADMIN', 'SETPCAP','BPF']
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  # - name: fluentbit_debian_instance_11
  #   #geerlingguy/docker-centos8-ansible:latest
  #   image: geerlingguy/docker-debian11-ansible
  #   privileged: true
  #   capabilities:
  #     - SYS_ADMIN
  #     - SETPCAP
  #   command: /sbin/init
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   #  - /var/lib/containerd
  #   cgroupns_mode: host
  #   #tmpfs:
  #   #  - /run
  #   #  - /tmp
  #- name: instance
  - name: fluentbit_ubuntu_instance_2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    capabilities:
      - SYS_ADMIN
      - SETPCAP
    pre_build_image: true
    cgroupns_mode: host

provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    connection: docker
    v: 2
