---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: fluentbit_stretch
    image: debian:stretch
    command: /sbin/init
    tmpfs: ['/tmp', '/run', '/run/lock']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - fluentbit
provisioner:
  name: ansible
  playbook:
    converge: converge.yml
    verify: verify.yml
verifier:
  name: testinfra
  options:
    connection: docker
    v: 2
lint: |
  set -e
  yamllint .
  ansible-lint -v
